#ifndef __GAMESTATE_HPP__
#define __GAMESTATE_HPP__

enum GameState {
	STATE_SETUP,
	STATE_GET_INPUT,
	STATE_PARSE_INPUT,
	STATE_VALIDATE_INPUT,
	STATE_PROCESS_EVENTS,
	STATE_QUICK_CLEANUP,
	STATE_UPDATE_DISPLAY,
	STATE_FULL_CLEANUP,
	STATE_GAME_OVER
};

#endif